### PR TITLE
Ocd 988

### PR DESCRIPTION
**Pull request by kekey1**
Please review these changes and let me know what you think. Feel free to pull them into your own environment to try them. 

NOTE: You'll have to modify your tomcat startup (in catalina.sh for someone using tomcat commandline and in the "Arguments" tab of the Tomcat Run Configuration in Eclipse)

**-Djndi.name=java:comp/env/jdbc/openchpl**

You very likely already have several -Dsomething arguments that look similar to what's below... just add this to the list:
-Dcatalina.base="C:\Users\kekey\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0" -Dcatalina.home="C:\Users\kekey\apache-tomcat-8.0.24" -Dwtp.deploy="C:\Users\kekey\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps" -Djava.endorsed.dirs="C:\Users\kekey\apache-tomcat-8.0.24\endorsed"

### CODE REVIEW

**Comment by dlucas1** [comment]
In your comment about adding the arguments to the Tomcat Run Configuration (or catalina.sh), I see that you mentioned adding this line:
-Djava.endorsed.dirs="C:\Users\kekey\apache-tomcat-8.0.24\endorsed"

This exact line should already be present - did you intend to add it a second time?

**Comment by andlar** [comment]
I read the comment as "Add the -Djndi argument to catalina.sh where the list that looks something like the one below is". That said, I think we're going to add the environment variable as part of the setenv.sh script, once we're ready to actually deploy it

**Comment by dlucas1** [comment]
I noticed that there are separate tmp0 and tmp1 folders on my local hard drive, as seen below:
\workspace.metadata.plugins\org.eclipse.wst.server.core\tmp0
\workspace.metadata.plugins\org.eclipse.wst.server.core\tmp1

That's why I thought Katy was suggesting adding arguments that map Catalina arguments to those folders. I wonder why we have a tmp0 and tmp1 folder? I see the log that I would expect to see for chpl-service as shown in \org.eclipse.wst.server.core\tmp0\logs but when I look at the log in tmp1, it is mostly blank. I noticed that Eclipse is currently configured to point to tmp1 in the command line arguments. If that's the case, then why are my logs (with all the GET and POST data from running my server) showing under tmp0? Is there a configuration setting somewhere else that is overriding Eclipse's command-line arguments?

**Comment by andlar** [comment]
@kekey1 & @dlucas1 Is this PR still relevant? Or did Dan's other work overcome this one?

**Comment by kekey1** [comment]
Not relevant any longer

**Pull request closed without merging**
